weights: /content/ScaledYOLOv4/weights/yolov4-p5.pt
cfg: /content/ScaledYOLOv4/models/yolov4-p5.yaml
data: /content/Diatom-Non-neuronal-Cognition/Dataset/30_bbg/related_files/diatom.yaml
hyp: data/hyp.finetune.yaml
epochs: 300
batch_size: 8
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
total_batch_size: 8
world_size: 1
global_rank: -1
